default:\
	:tc=pygments:
pygments:\
	:tc=pygments-parser:tc=htags:
common:\
	:skip=tags,TAGS,ID,gtags.files,cscope.files,cscope.out,cscope.po.out,cscope.in.out,*.orig,*.rej,*.bak,*.swp,*.tmp,*.zip,*.gz,*.bz2,*.xz,*.lzh,*.Z,*.tgz,*.min.js,*min.css,node_modules/:
pygments-parser:\
	:tc=common:\
	:ctagscom=/usr/bin/ctags:\
	:pygmentslib=$libdir/gtags/pygments-parser.so:\
	:langmap=Bash\:.sh.ksh.bash.ebuild.eclass:\
	:langmap=CoffeeScript\:.coffee:\
	:langmap=Haml\:.haml:\
	:langmap=JavaScript\:.js:\
	:langmap=Lua\:.lua.wlua:\
	:langmap=Python\:.py.pyw.sc.tac.sage:\
	:langmap=Ruby\:.rb.rbw.rake.gemspec.rbx.duby:\
	:langmap=TypeScript\:.ts:\
	:langmap=Vim\:.vim:\
	:gtags_parser=Bash\:$pygmentslib:\
	:gtags_parser=CoffeeScript\:$pygmentslib:\
	:gtags_parser=Haml\:$pygmentslib:\
	:gtags_parser=JavaScript\:$pygmentslib:\
	:gtags_parser=Lua\:$pygmentslib:\
	:gtags_parser=Python\:$pygmentslib:\
	:gtags_parser=Ruby\:$pygmentslib:\
	:gtags_parser=TypeScript\:$pygmentslib:\
	:gtags_parser=Vim\:$pygmentslib:
htags:\
	::
