set -g default-command "${SHELL}"

# Renumber windows on deletion
set -g renumber-windows on

# Start windows and panes indexes at 1
set -g base-index 1
setw -g pane-base-index 1

# Enable Vim mode
setw -g mode-keys vi

# Clear screen when a process is running
bind C-l send-keys -R

# Clear scrollback history
bind C-k clear-history

# Set the history limit to 10000
set -g history-limit 10000

# Set Ctrl+Space as the Prefix
set -g prefix C-Space

# Easily move windows around
bind -r P swap-window -d -t -1
bind -r N swap-window -d -t +1

# Quickswitch to Dotfiles
bind u run-shell "\
  tmux has-session -t dotfiles 2>/dev/null || (\
    tmux new-session -d -s dotfiles -c ~/.files -n code 'nvim' &&\
    tmux new-window -t dotfiles -n shell -c ~/.files\
  );\
  tmux switch-client -t dotfiles;\
  tmux select-window -t dotfiles:code\
"

# TMUX Fingers plugin
set -g @plugin 'Morantron/tmux-fingers'

# TMUX Srcery theme
set -g @plugin 'srcery-colors/srcery-tmux'

# Highlight Prefix
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

if "test ! -d ~/.tmux/plugins/tpm" \
	   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX Plugin Manager
run '~/.tmux/plugins/tpm/tpm'
